"use strict";

import { familyCss } from "./css.ts";
import { family } from "./families/muted.ts";
import { paletteCss } from "./palette.ts";

// css/components/icons.css as it should be: the --icon-* palette (light on
// :root, dark under html[data-theme="dark"]; the options screen's <Icon>s
// paint their role colours with it) and the family's images for the popup's
// .icon classes (css.ts). scripts/icons-css.mjs writes it to disk, and
// tests/iconsStylesheet.test.ts fails when the file on disk is stale.
// Pure and deterministic: the same family gives the same text, \n endings.
const HEADER = "/* generated by scripts/icons-css.mjs from src/icons/families/muted.ts — do not edit; run `npm run icons:css` */\n";

export function iconsCss() : string {
	return HEADER + "\n" + paletteCss(":root", "light") + paletteCss('html[data-theme="dark"]', "dark") + "\n" + familyCss(family);
}
