"use strict";

// Unit tests for src/icons/stylesheet.ts: the generated css/components/icons.css
// (scripts/icons-css.mjs) and its freshness against the family it is made from.

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { iconsCss } from "../src/icons/stylesheet.ts";
import { familyCss } from "../src/icons/css.ts";
import { family } from "../src/icons/families/muted.ts";

const FILE = new URL("../css/components/icons.css", import.meta.url);

test("starts with the do-not-edit header naming the script, the family and the npm script", () => {
	const head = iconsCss().split("\n")[0];
	assert.match(head, /^\/\* generated by scripts\/icons-css\.mjs from src\/icons\/families\/muted\.ts/);
	assert.match(head, /do not edit; run `npm run icons:css` \*\/$/);
});

test("the family's images follow the header, and nothing else", () => {
	const css = iconsCss(), icons = familyCss(family);
	assert.ok(css.endsWith(icons));
	assert.ok(css.indexOf(icons) === css.indexOf("\n") + 2);
	assert.ok(!css.includes("--icon-") && !css.includes("data-theme"));
});

test("deterministic, \\n line endings, one trailing newline", () => {
	const css = iconsCss();
	assert.equal(iconsCss(), css);
	assert.ok(!css.includes("\r"));
	assert.ok(css.endsWith("}\n") && !css.endsWith("\n\n"));
});

test("css/components/icons.css is up to date (else: run npm run icons:css)", () => {
	let disk = "";
	try {
		disk = readFileSync(FILE, "utf8");
	} catch {
		// missing: stale too
	}
	// a checkout may have turned the endings into \r\n; the content is what counts
	assert.ok(disk.replace(/\r\n/g, "\n") === iconsCss(), "css/components/icons.css is stale: run npm run icons:css");
});
