import * as React from "react";

export interface ITabOptions {
	animations: boolean,
	badge: boolean,
	compact: boolean,
	dark: boolean,
	hideWindows: boolean,
	openInOwnTab: boolean,
	sessionsFeature: boolean,
	tabHeight: number,
	tabLimit: number,
	tabWidth: number,
	tabactions: boolean,
	windowTitles: boolean,

	tabLimitText: () => void,
	changeTabLimit: (e: React.ChangeEvent<HTMLInputElement>) => void,
	tabWidthText: () => void,
	changeTabWidth: (e: React.ChangeEvent<HTMLInputElement>) => void,
	tabHeightText: () => void,
	changeTabHeight: (e: React.ChangeEvent<HTMLInputElement>) => void,
	darkText: () => void,
	toggleDark: () => void,
	compactText: () => void,
	toggleCompact: () => void,
	animationsText: () => void,
	toggleAnimations: () => void,
	windowTitlesText: () => void,
	toggleWindowTitles: () => void,
	sessionsText: () => void,
	toggleSessions: () => void,
	exportSessionsText: () => void,
	exportSessions: () => void,
	importSessionsText: () => void,
	importSessions: (e: React.ChangeEvent<HTMLInputElement>) => void,
	badgeText: () => void,
	toggleBadge: () => void,
	openInOwnTabText: () => void,
	toggleOpenInOwnTab: () => void,
	hideText: () => void,
	toggleHide: () => void,
	tabActionsText: () => void,
	toggleTabActions: () => void
	getTip: () => string
}