// Generates src/popup/psl.ts from the Public Suffix List.
//
//   node scripts/psl.mjs     (npm run psl)
//
// Dev-time only: the extension never fetches the list, it ships the checked-in module.

import { writeFileSync } from "node:fs";

const URL_PSL = "https://publicsuffix.org/list/public_suffix_list.dat";
const OUT = "src/popup/psl.ts";

const res = await fetch(URL_PSL, { redirect: "follow" });
if (!res.ok) throw new Error("download failed: " + res.status + " " + res.statusText);
const text = await res.text();

const icann = [];
const priv = [];
let section = null;
for (const raw of text.split(/\r?\n/)) {
	const line = raw.trim();
	if (line.startsWith("//")) {
		if (line.includes("===BEGIN ICANN DOMAINS===")) section = icann;
		else if (line.includes("===END ICANN DOMAINS===")) section = null;
		else if (line.includes("===BEGIN PRIVATE DOMAINS===")) section = priv;
		else if (line.includes("===END PRIVATE DOMAINS===")) section = null;
		continue;
	}
	if (!line || !section) continue;
	section.push(ascii(line.split(/\s+/)[0].toLowerCase()));
}

// "*." and "!" stay aside while the rest becomes punycode
function ascii(rule) {
	let prefix = "";
	let rest = rule;
	if (rest.startsWith("!")) {
		prefix = "!";
		rest = rest.slice(1);
	} else if (rest.startsWith("*.")) {
		prefix = "*.";
		rest = rest.slice(2);
	}
	return prefix + new URL("http://" + rest).hostname;
}

// Cloud hosting domains whose PRIVATE rules are one per region or service
// (561 under amazonaws.com alone). A window name never needs that detail:
// every such host is the one site, so the sub-rules collapse into the domain
// itself as a single private rule. windowName.ts names most of them (AWS,
// Azure, ...) in its table before the list is consulted.
const COLLAPSE = [
	"amazonaws.com", "amazoncognito.com", "elasticbeanstalk.com", "on.aws", "sagemaker.aws",
	"azurewebsites.net", "azurestaticapps.net", "scw.cloud", "k2.cloud", "replit.dev", "crm.dev",
	"int.apple", "mythic-beasts.com", "evennode.com", "thingdust.io", "massivegrid.net", "fastly.net", "ngrok.io",
];
function collapse(rules) {
	const body = (r) => r.replace(/^(\*\.|!)/, "");
	const kept = rules.filter((r) => !COLLAPSE.some((c) => body(r).endsWith("." + c)));
	return [...new Set([...kept, ...COLLAPSE])];
}

// Rules grouped by TLD with the TLD stripped: { jp: "ac co *.kawasaki !city.kawasaki", uk: "co org" }
function pack(rules) {
	const groups = new Map();
	for (const r of rules) {
		const prefix = r.startsWith("!") ? "!" : r.startsWith("*.") ? "*." : "";
		const body = r.slice(prefix.length);
		const dot = body.lastIndexOf(".");
		if (dot < 0) continue; // single-label TLDs need no list: any single label is a public suffix by default
		const tld = body.slice(dot + 1);
		if (!groups.has(tld)) groups.set(tld, []);
		groups.get(tld).push(prefix + body.slice(0, dot));
	}
	const lines = [...groups.keys()].sort().map((tld) => `\t${JSON.stringify(tld)}: ${JSON.stringify([...new Set(groups.get(tld))].sort().join(" "))},`);
	return lines.length ? `{\n${lines.join("\n")}\n}` : "";
}

const icannRules = pack(icann);
const privRules = pack(collapse(priv));
if (!icannRules || !privRules) throw new Error("PSL sections not found");

const out = `"use strict";

// The Public Suffix List, as the rules windowName.ts needs.
// Source: ${URL_PSL}
// Downloaded: ${new Date().toISOString().slice(0, 10)}
// Licence: Mozilla Public License 2.0, https://mozilla.org/MPL/2.0/
// Generated by scripts/psl.mjs, do not edit.
// Format: object keyed by tld; each value is the space-separated rules minus their final
// ".tld" ("*." and "!" prefixes kept). Single-label rules are omitted (default rule).

// ICANN rules
export const ICANN: Record<string, string> = ${icannRules};

// PRIVATE rules: hosting suffixes where every tenant is its own site
export const PRIVATE: Record<string, string> = ${privRules};
`;
writeFileSync(OUT, out);
console.log(`${OUT}: ${Buffer.byteLength(out)} bytes`);
